[2025-01-23T06:28:25.963+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-23T06:28:25.974+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9843500346_2025-01-23T06-27-17-789018Z.find_reason_for_unanswered scheduled__2025-01-23T06:27:17.789018+00:00 [queued]>
[2025-01-23T06:28:25.978+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9843500346_2025-01-23T06-27-17-789018Z.find_reason_for_unanswered scheduled__2025-01-23T06:27:17.789018+00:00 [queued]>
[2025-01-23T06:28:25.978+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-23T06:28:25.983+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): find_reason_for_unanswered> on 2025-01-23 06:27:17.789018+00:00
[2025-01-23T06:28:25.988+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=39750) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-23T06:28:25.989+0000] {standard_task_runner.py:72} INFO - Started process 39751 to run task
[2025-01-23T06:28:25.989+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9843500346_2025-01-23T06-27-17-789018Z', 'find_reason_for_unanswered', 'scheduled__2025-01-23T06:27:17.789018+00:00', '--job-id', '1198', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmp6zrmiye8']
[2025-01-23T06:28:25.990+0000] {standard_task_runner.py:105} INFO - Job 1198: Subtask find_reason_for_unanswered
[2025-01-23T06:28:26.012+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9843500346_2025-01-23T06-27-17-789018Z.find_reason_for_unanswered scheduled__2025-01-23T06:27:17.789018+00:00 [running]> on host 680cb867086b
[2025-01-23T06:28:26.047+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9843500346_2025-01-23T06-27-17-789018Z' AIRFLOW_CTX_TASK_ID='find_reason_for_unanswered' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T06:27:17.789018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T06:27:17.789018+00:00'
[2025-01-23T06:28:26.047+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-23T06:28:26.048+0000] {logging_mixin.py:190} INFO - demo-scheduled-from-ui-global6df61277-a15d-4866-bcc3-c42433a08d14
[2025-01-23T06:28:26.049+0000] {logging_mixin.py:190} INFO - cause_txt: switch_off
[2025-01-23T06:28:26.052+0000] {base.py:84} INFO - Retrieving connection 'aicallagent'
[2025-01-23T06:28:26.056+0000] {sql.py:544} INFO - Running statement: UPDATE user_details SET status = 'switch_off', modified_on_utc = now() at time zone 'utc' WHERE caller_id = 'demo-scheduled-from-ui-global6df61277-a15d-4866-bcc3-c42433a08d14', parameters: None
[2025-01-23T06:28:26.057+0000] {sql.py:553} INFO - Rows affected: 1
[2025-01-23T06:28:26.057+0000] {logging_mixin.py:190} INFO - Marked record demo-scheduled-from-ui-global6df61277-a15d-4866-bcc3-c42433a08d14 as switch_off.
[2025-01-23T06:28:26.058+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-23T06:28:26.063+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-23T06:28:26.063+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9843500346_2025-01-23T06-27-17-789018Z, task_id=find_reason_for_unanswered, run_id=scheduled__2025-01-23T06:27:17.789018+00:00, execution_date=20250123T062717, start_date=20250123T062825, end_date=20250123T062826
[2025-01-23T06:28:26.082+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-23T06:28:26.092+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-23T06:28:26.092+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
